[window]
opacity = 0
decorations = "none"

[font]
size = 11

[font.normal]
family = "Liga SFMono Nerd Font"
style = "Regular"

[font.bold]
family = "Liga SFMono Nerd Font"
style = "Bold"

[font.italic]
family = "jetBrainsMonoNL Nerd Font Mono"
style = "Italic"

# [colors.primary]
# background = "#000001"
# foreground = "#ffffff"
#
# [colors.cursor]
# text = "#000000"
# cursor = "#ffffff"
#
# [colors.normal]
# black = "#1c1c1c"
# red = "#D7154F"
# green = "#9acc79"
# yellow = "#d0d26b"
# blue = "#1549D7"
# magenta = "#a488d9"
# cyan = "#04F7F7"
# white = "#8d8d8d"

[colors.primary]
background = '#0c0c16'
# background = '#1a1b26' -- tokio night
foreground = '#a9b1d6'

# Normal colors
[colors.normal]
black   = '#32344a'
red     = '#f7768e'
green   = '#9ece6a'
yellow  = '#e0af68'
blue    = '#7aa2f7'
magenta = '#ad8ee6'
cyan    = '#449dab'
white   = '#787c99'

# Bright colors
[colors.bright]
black   = '#444b6a'
red     = '#ff7a93'
green   = '#b9f27c'
yellow  = '#ff9e64'
blue    = '#7da6ff'
magenta = '#bb9af7'
cyan    = '#0db9d7'
white   = '#acb0d0'


[[keyboard.bindings]]
key = "1"
mods = "Control"
chars = "\u0188"

[[keyboard.bindings]]
key = "2"
mods = "Control"
chars = "\u0189"


[[keyboard.bindings]]
key = "3"
mods = "Control"
chars = "\u018A"

[[keyboard.bindings]]
key = "4"
mods = "Control"
chars = "\u018B"

[[keyboard.bindings]]
key = "5"
mods = "Control"
chars = "\u018C"

[[keyboard.bindings]]
key = "6"
mods = "Control"
chars = "\u018D"

[[keyboard.bindings]]
key = "7"
mods = "Control"
chars = "\u018E"

[[keyboard.bindings]]
key = "8"
mods = "Control"
chars = "\u018F"

[[keyboard.bindings]]
key = "9"
mods = "Control"
chars = "\u0190"

[[keyboard.bindings]]
key = "h"
mods = "Control|Shift"
chars = "\u0191"

[[keyboard.bindings]]
key = "j"
mods = "Control|Shift"
chars = "\u0192"

[[keyboard.bindings]]
key = "k"
mods = "Control|Shift"
chars = "\u0193"

[[keyboard.bindings]]
key = "l"
mods = "Control|Shift"
chars = "\u0194"



